[theme]
base = "dark"
primaryColor = "#4F8BF9"       # optional: your accent color
backgroundColor = "#0E1117"    # optional: background
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"